name: simple workflow-1st-run-rin

#on:
 # push:

on:
  push:
    branches: 
      - main
      - develop
      - release
      - hotfix
      - bugfix
      - release/**
  workflow_dispatch: 

jobs:
  ab-ch: # we can give naming convention
    runs-on: ubuntu-latest

    steps:
      - name: print message
        run: echo "run the code"

# A workflow contains:
#   n number of jobs
#
# Jobs contain n number of steps
#
# Steps contain n number of tasks (also known as actions)
