name: simple workflow-1st-run-rin

#on:
 # push:

on:
  push:
    branches: [ "main" ]

jobs:
  ab-ch: # we can give naming convention
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        uses: actions/checkout@4
      - name: print message
        run: echo "run the code"

# A workflow contains:
#   n number of jobs
#
# Jobs contain n number of steps
#
# Steps contain n number of tasks (also known as actions)
